### ISSUE TITLE
Contribute Serde-avro upstream

### ISSUE THREAD

**Issue by jadbox** [dflemstr/rq#156]
It would be great to get this work into Serde proper. I've put together a Serde issue to kickstart a conversation.

https://github.com/serde-rs/serde/issues/887

**Comment by dtolnay** [comment]
Oh @dflemstr, one thing I would like is a landing page for serde-avro. I think that's why I didn't link it from the Serde website. Right now none of these are really a suitable landing page for a link to point to:

- https://github.com/dflemstr/rq
- https://github.com/dflemstr/rq/tree/master/serde-avro
- https://crates.io/crates/serde-avro
- https://docs.rs/serde-avro

Can you either drop a readme in the serde-avro directory or flesh out the rustdoc a bit?

**Comment by jadbox** [comment]
I'd recommend that serde-avro could be promoted to its own repo. :]

**Comment by mikaelstaldal** [comment]
Now there is avro-rs.

**Comment by dflemstr** [comment]
Going to close this, avro-rs is a good alternative
